cable_positioning:
  action_type: "cable"

  move_to_cable_removal:
    skill_type: "ur_move_to"
    goal_frame: "cable_removal"
    tool_frame: "open_tip"
    acceleration: 10
    velocity: 3

  cable_gripper_position:
    skill_type: "robotiq_gripper_move"
    property_id: "pos_50_force_100_vel_100" # pos_10_force_10_vel_20   (pos_mm_force_N_vel_m/s)

  down_to_removal:
    skill_type: "ur_linear_move"
    reference_frame: "real_tool"
    tool_frame: "real_tool"
    traslation: [0,0,0.065]
    rotation: [0,0,0,1]
    velocity: 0.5
    acceleration: 1
    n_point: 1

  close_gripper:
    skill_type: "robotiq_gripper_move"
    property_id: "close"

  up_from_removal:
    skill_type: "ur_linear_move"
    reference_frame: "real_tool"
    tool_frame: "real_tool"
    traslation: [0,0,-0.07]
    rotation: [0,0,0,1]
    velocity: 0.3
    acceleration: 0.5
    n_point: 1

  move_to_cable_insertion:
    # skill_type: "ur_move_to"
    # goal_frame: "cable_insertion"
    # tool_frame: "open_tip"
    # acceleration: 10
    # velocity: 3
    skill_type: "ur_linear_move"
    reference_frame: "reference"
    tool_frame: "real_tool"
    traslation: [0,-0.024,0]
    rotation: [0,0,0,1]
    velocity: 0.3
    acceleration: 0.5
    n_point: 1

  down_to_insertion:
    skill_type: "ur_linear_move"
    reference_frame: "base"
    tool_frame: "real_tool"
    traslation: [0,0,0.042]
    rotation: [0,0,0,1]
    velocity: 0.5
    acceleration: 1
    n_point: 1

  insertion:
    skill_type: "ur_linear_move"
    reference_frame: "base"
    tool_frame: "real_tool"
    traslation: [0,0,0.015]
    rotation: [0,0,0,1]
    velocity: 0.1
    acceleration: 5
    n_point: 1

  push:
    skill_type: "ur_simple_touch_tool"
    MOVEX: 0.0
    MOVEY: 0.0
    MOVEZ: 1.0
    VELOCITY: 0.05
    ACCELERATION: 0.5
    FORCE: 15

  gripper_position_1:
    skill_type: "robotiq_gripper_move"
    property_id: "pos_35_force_100_vel_100" # pos_10_force_10_vel_20   (pos_mm_force_N_vel_m/s)

  rotation:
    skill_type: "ur_linear_move"
    reference_frame: "real_tool"
    tool_frame: "real_tool"
    traslation: [0,0,0]
    rotation: [0, 0, -0.8660254, 0.5]
    velocity: 1
    acceleration: 5
    n_point: 1

  gripper_position_2:
    skill_type: "robotiq_gripper_move"
    property_id: "pos_50_force_100_vel_100" # pos_10_force_10_vel_20   (pos_mm_force_N_vel_m/s)

  rotation_2:
    skill_type: "ur_linear_move"
    reference_frame: "real_tool"
    tool_frame: "real_tool"
    traslation: [0,0,0]
    rotation: [0, 0, 0.1736482, 0.9848078]
    velocity: 1
    acceleration: 5
    n_point: 1

  up_from_insertion:
    skill_type: "ur_linear_move"
    reference_frame: "real_tool"
    tool_frame: "real_tool"
    traslation: [0,0,-0.08]
    rotation: [0,0,0,1]
    velocity: 0.5
    acceleration: 5
    n_point: 1
