identification_test:
  action_type: "ident_test"

  close_gripper:
    skill_type: "robotiq_gripper_move"
    property_id: "pos_0_force_100_vel_100" # pos_10_force_10_vel_20   (pos_mm_force_N_vel_m/s)

  touch:
    skill_type: "ur_simple_touch_tool"
    MOVEX: 0.0
    MOVEY: 0.0
    MOVEZ: 1.0
    VELOCITY: 0.03
    ACCELERATION: 0.5
    FORCE: 10

  move_to_blue_button:
    skill_type: "ur_move_to"
    goal_frame: "blue_button_approach"
    tool_frame: "open_tip"
    acceleration: 10
    velocity: 3

  move_to_red_button:
    skill_type: "ur_move_to"
    goal_frame: "red_button_approach"
    tool_frame: "open_tip"
    acceleration: 10
    velocity: 3

  move_to_slider:
    skill_type: "ur_move_to"
    goal_frame: "slider_approach"
    tool_frame: "open_tip"
    acceleration: 10
    velocity: 3

  move_to_door:
    skill_type: "ur_move_to"
    goal_frame: "door_approach"
    tool_frame: "open_tip"
    acceleration: 10
    velocity: 3

  move_to_cable_removal:
    skill_type: "ur_move_to"
    goal_frame: "cable_removal"
    tool_frame: "open_tip"
    acceleration: 10
    velocity: 3

  move_to_cable_picking:
    skill_type: "ur_move_to"
    goal_frame: "cable_picking"
    tool_frame: "open_tip"
    acceleration: 10
    velocity: 3

  move_to_probe:
    skill_type: "ur_move_to"
    goal_frame: "probe_approach"
    tool_frame: "open_tip"
    acceleration: 10
    velocity: 3

  move_to_camera_pose:
    skill_type: "ur_move_to"
    goal_frame: "camera_pose"
    tool_frame: "open_tip"
    acceleration: 10
    velocity: 3
