tf_params:
  - {name: "camera_pose_transf",            frame: "base",           position: [-0.276, -0.475, 0.505], quaternion: [0.000, 0.000, 1.000, 0.000]}
  - {name: "reference_transf",                     frame: "base",           position: [-0.334, -0.726, 0.968], quaternion: [0.002, -0.001, 0.207, 0.978]}
